# Generated by Django 4.2.11 on 2024-12-03 13:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields
from django.db import migrations, models

import smartsetter_utils.ssot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=128)),
                ("city", models.CharField(db_index=True, max_length=128)),
                ("zipcode", models.CharField(db_index=True, max_length=32)),
                ("phone", models.CharField(db_index=True, max_length=32, null=True)),
                ("state", models.CharField(db_index=True, max_length=16)),
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("email", models.CharField(db_index=True, max_length=64, null=True)),
                (
                    "verified_phone",
                    models.CharField(db_index=True, max_length=32, null=True),
                ),
                (
                    "verified_phone_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sheet", "Sheet"),
                            ("phone_validator", "Phone Validator API"),
                            ("clay", "Clay"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("office_name", models.CharField(db_index=True, max_length=128)),
                ("years_in_business", models.PositiveSmallIntegerField(db_index=True)),
                ("listing_transactions_count", models.PositiveIntegerField(default=0)),
                ("selling_transactions_count", models.PositiveIntegerField(default=0)),
                ("listing_production", models.PositiveBigIntegerField(default=0)),
                ("selling_production", models.PositiveBigIntegerField(default=0)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("hubspot_id", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                smartsetter_utils.ssot.models.base_models.RealityDBBase,
                django_lifecycle.mixins.LifecycleModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("marks", models.JSONField(default=list)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=smartsetter_utils.ssot.models.brand.brand_icon_upload_to,
                    ),
                ),
                (
                    "icon_circular",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=smartsetter_utils.ssot.models.brand.brand_icon_upload_to,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MLS",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                ("table_name", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=128)),
                ("city", models.CharField(db_index=True, max_length=128)),
                ("zipcode", models.CharField(db_index=True, max_length=32)),
                ("phone", models.CharField(db_index=True, max_length=32, null=True)),
                ("state", models.CharField(db_index=True, max_length=16)),
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("office_id", models.CharField(max_length=128)),
                ("hubspot_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "mls",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="ssot.mls",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                smartsetter_utils.ssot.models.base_models.RealityDBBase,
                django_lifecycle.mixins.LifecycleModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("mls_number", models.CharField(db_index=True, max_length=32)),
                ("address", models.CharField(db_index=True, max_length=128)),
                ("district", models.CharField(db_index=True, max_length=128)),
                ("community", models.CharField(db_index=True, max_length=128)),
                ("city", models.CharField(db_index=True, max_length=128)),
                ("county", models.CharField(db_index=True, max_length=64)),
                ("zipcode", models.CharField(db_index=True, max_length=32)),
                ("state_code", models.CharField(db_index=True, max_length=16)),
                ("list_price", models.PositiveBigIntegerField(db_index=True)),
                ("sold_price", models.PositiveBigIntegerField(db_index=True)),
                ("days_on_market", models.IntegerField(db_index=True)),
                ("closed_date", models.DateField(db_index=True)),
                (
                    "listing_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_transactions",
                        to="ssot.agent",
                    ),
                ),
                (
                    "listing_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_transactions",
                        to="ssot.office",
                    ),
                ),
                (
                    "mls",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="ssot.mls",
                    ),
                ),
                (
                    "selling_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selling_transactions",
                        to="ssot.agent",
                    ),
                ),
                (
                    "selling_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selling_transactions",
                        to="ssot.office",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                smartsetter_utils.ssot.models.base_models.RealityDBBase,
                django_lifecycle.mixins.LifecycleModelMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="ssot.brand",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="mls",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="ssot.mls",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="ssot.office",
            ),
        ),
        migrations.CreateModel(
            name="ListingTransactionProxy",
            fields=[],
            options={
                "verbose_name": "Listing Transaction",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ssot.transaction",),
        ),
        migrations.CreateModel(
            name="SellingTransactionProxy",
            fields=[],
            options={
                "verbose_name": "Selling Transaction",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ssot.transaction",),
        ),
    ]
