# Generated by Django 4.2.11 on 2024-12-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="job_title",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
