# Generated by Django 4.2.11 on 2025-02-24 07:15

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0002_agent_job_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zipcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("zipcode", models.CharField(db_index=True, max_length=16)),
                ("city", models.CharField(max_length=64)),
                ("state", models.CharField(max_length=16)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
