# Generated by Django 4.2.11 on 2025-05-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0003_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                default="reality",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="office",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                default="reality",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                default="reality",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="mls",
            name="id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
