# Generated by Django 4.2.11 on 2025-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0006_alter_agent_address_alter_agent_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
