# Generated by Django 4.2.11 on 2025-06-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0007_agent_raw_data_office_raw_data_transaction_raw_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="email",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                db_index=True,
                default="reality",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="state",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="status",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="years_in_business",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="zipcode",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="code",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                db_index=True,
                default="reality",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="state",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="status",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="zipcode",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                db_index=True,
                default="reality",
                max_length=32,
            ),
        ),
    ]
