# Generated by Django 4.2.11 on 2025-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0008_alter_agent_city_alter_agent_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="email",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="job_title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="office_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
