# Generated by Django 4.2.11 on 2025-06-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0009_alter_agent_email_alter_agent_job_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="raw_data",
        ),
    ]
