# Generated by Django 4.2.11 on 2025-07-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0010_remove_transaction_raw_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="mls",
            name="company_hubspot_internal_value",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="mls",
            name="contact_hubspot_internal_value",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
