# Generated by Django 4.2.11 on 2025-10-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0012_agentofficethrough_agent_office_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="lease_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="property_type",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
