# Generated by Django 4.2.11 on 2025-10-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0013_transaction_lease_price_transaction_property_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="listing_contract_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="closed_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
