# Generated by Django 4.2.11 on 2025-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0014_transaction_listing_contract_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="tenure",
            field=models.DurationField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="tenure_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="tenure_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
