# Generated by Django 4.2.11 on 2025-11-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0015_agent_tenure_agent_tenure_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mls",
            name="data_available_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
