# Generated by Django 4.2.11 on 2025-11-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0016_mls_data_available_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="last_activity_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="most_transacted_city",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="total_production",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agent",
            name="total_transactions_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="office_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
    ]
