# Generated by Django 4.2.11 on 2025-11-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0017_agent_last_activity_date_agent_most_transacted_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mls",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                db_index=True,
                default="constellation",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                db_index=True,
                default="constellation",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                db_index=True,
                default="constellation",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[("reality", "Reality"), ("constellation", "Constellation1")],
                db_index=True,
                default="constellation",
                max_length=32,
            ),
        ),
    ]
