# Generated by Django 4.2.11 on 2025-11-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0018_mls_source_alter_agent_source_alter_office_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="colisting_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colisting_transactions",
                to="ssot.agent",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="colisting_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colisting_transactions",
                to="ssot.office",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="coselling_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coselling_transactions",
                to="ssot.agent",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="coselling_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coselling_transactions",
                to="ssot.office",
            ),
        ),
    ]
