# Generated by Django 4.2.11 on 2025-11-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0019_transaction_colisting_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="total_production",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
