# Generated by Django 4.2.11 on 2025-11-26 08:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import smartsetter_utils.ssot.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0020_alter_agent_total_production"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentOfficeMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="agent",
            name="office_history",
        ),
        migrations.AddField(
            model_name="agent",
            name="likelihood_to_move",
            field=smartsetter_utils.ssot.fields.PercentageNumberField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="office",
            name="churn_percentage",
            field=smartsetter_utils.ssot.fields.PercentageNumberField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="total_production",
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="agent",
            name="total_transactions_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name="AgentOfficeThrough",
        ),
        migrations.AddField(
            model_name="agentofficemovement",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="office_movements",
                to="ssot.agent",
            ),
        ),
        migrations.AddField(
            model_name="agentofficemovement",
            name="from_office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="out_movements",
                to="ssot.office",
            ),
        ),
        migrations.AddField(
            model_name="agentofficemovement",
            name="to_office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_movements",
                to="ssot.office",
            ),
        ),
    ]
