# Generated by Django 4.2.11 on 2025-11-27 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0021_agentofficemovement_remove_agent_office_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="likelihood_to_move",
            field=models.FloatField(
                blank=True,
                db_index=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="office",
            name="churn_score",
            field=models.FloatField(
                blank=True,
                db_index=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(30)],
            ),
        ),
    ]
