# Generated by Django 4.2.11 on 2025-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0022_agent_likelihood_to_move_office_churn_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="city",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="community",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="district",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
