# Generated by Django 4.2.11 on 2025-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0024_albertaabagent_albuquerquenmagent_austinagent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="listing_transactions_count",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="agent",
            name="selling_transactions_count",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="agent",
            name="total_transactions_count",
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
