# Generated by Django 4.2.11 on 2026-01-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0024_constellationaustinagent_constellationbeachesagent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("agent", "Agent"), ("broker", "Broker"), ("other", "Other")],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
    ]
