# Generated by Django 4.2.11 on 2026-01-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0025_agent_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="mls",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
