# Generated by Django 4.2.11 on 2026-03-24 11:21

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields
import smartsetter_utils.ssot.models.base_models


class Migration(migrations.Migration):

    dependencies = [
        ("ssot", "0026_mls_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstellationSanantonioAgent",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("reality", "Reality"),
                            ("constellation", "Constellation1"),
                            ("nureality", "Reality API"),
                            ("trestle", "Trestle"),
                            ("mlsgrid", "MLSGrid"),
                        ],
                        db_index=True,
                        default="constellation",
                        max_length=32,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=32, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, max_length=16, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                ("hubspot_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "raw_mls_modification_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("modification_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "originating_system_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "source_system_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "source_system_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "member_firstname",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "member_middlename",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "member_lastname",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_index=True, max_length=256, null=True
                    ),
                ),
                (
                    "verified_phone",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "verified_phone_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sheet", "Sheet"),
                            ("phone_validator", "Phone Validator API"),
                            ("clay", "Clay"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "member_directphone",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "member_homephone",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "member_preferred_phone",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "office_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=256, null=True
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "years_in_business",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("listing_transactions_count", models.PositiveIntegerField(default=0)),
                ("selling_transactions_count", models.PositiveIntegerField(default=0)),
                (
                    "total_transactions_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("listing_production", models.PositiveBigIntegerField(default=0)),
                ("selling_production", models.PositiveBigIntegerField(default=0)),
                (
                    "total_production",
                    models.PositiveBigIntegerField(db_index=True, default=0),
                ),
                ("tenure_start_date", models.DateField(blank=True, null=True)),
                ("tenure_end_date", models.DateField(blank=True, null=True)),
                ("tenure", models.DurationField(blank=True, db_index=True, null=True)),
                (
                    "most_transacted_city",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "likelihood_to_move",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("agent", "Agent"),
                            ("broker", "Broker"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "member_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "member_mlssecurity_class",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "member_mlsid",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "member_state_license",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "db_table": "ssot_agent_constellation_sanantonio",
                "managed": False,
            },
            bases=(
                smartsetter_utils.ssot.models.base_models.RealityDBBase,
                django_lifecycle.mixins.LifecycleModelMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_directphone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_firstname",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_homephone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_lastname",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_middlename",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_mlsid",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_mlssecurity_class",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_preferred_phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_state_license",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="member_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="modification_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="originating_system_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="raw_mls_modification_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="source_system_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="source_system_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="main_office_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="main_office_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="modification_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="office_broker_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="office_broker_mls_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="office_manager_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="office_mls_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="originating_system_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="raw_mls_modification_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="source_system_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="office",
            name="source_system_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="modification_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="originating_system_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="raw_mls_modification_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source_system_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source_system_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="brand",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="ssot.brand",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="office",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="ssot.office",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="colisting_agent",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colisting_transactions",
                to="ssot.agent",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="colisting_office",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colisting_transactions",
                to="ssot.office",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="coselling_agent",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coselling_transactions",
                to="ssot.agent",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="coselling_office",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coselling_transactions",
                to="ssot.office",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="listing_agent",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listing_transactions",
                to="ssot.agent",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="listing_office",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listing_transactions",
                to="ssot.office",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="selling_agent",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selling_transactions",
                to="ssot.agent",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="selling_office",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selling_transactions",
                to="ssot.office",
            ),
        ),
    ]
