member_type_patterns = [
    "cs administrative",
    "rets vendors",
    "waivered",
    "training",
    "mls access",
    "virtual tour",
    "mls",
    "rets vendor/access",
    "no member type",
    "staff",
    "mls only",
    "inspector",
    "board of directors, primary",
    "agent, personal assistant, secondary out of state",
    "staff, personal assistant",
    "non-mls",
    "appraiser, affiliate, mls only, secondary in state",
    "appraiser, secondary in state",
    "appraiser, affiliate, secondary in state",
    "affiliate, primary",
    "appraiser manager",
    "unlicensed office staff",
    "cleaning services",
    "notary public",
    "thompson participants",
    "non-realtor salesperson",
    "no access",
    "association",
    "licensed office assistant",
    "full service app",
    "rets vendor",
    "appraisermgr",
    "inactive",
    "public svc mbr",
    "metro only",
    "sold only",
    "appraiser trainees",
    "assessor",
    "mls secretary",
    "imls admin",
    "reciprocal",
    "vendor",
    "admin",
    "appraisers",
    "clerical",
    "greenville user",
    "piedmont user",
    "rets user",
    "administrative",
    "administrator",
    "advertising",
    "affiliate",
    "appraisal",
    "appraiser",
    "appraiser assistant",
    "appraiser with tax",
    "assistant",
    "assistant agent level",
    "assistant firm level",
    "assistant office level",
    "association staff",
    "associationstaff",
    "baseleveluser",
    "board staff",
    "book a showing",
    "construction/development",
    "designated realtor appraiser",
    "designatedrealtorappraiser",
    "estate sales services",
    "gift & retail services",
    "government designated realtor",
    "govt",
    "home warranty",
    "hospitality",
    "idx services",
    "inspectors",
    "insurance",
    "interior design/staging",
    "legal services",
    "lenders",
    "licensed assistant",
    "marketing",
    "military",
    "mls level",
    "mls only appraiser",
    "mlsonlyappraiser",
    "mls only realtor",
    "mls senior staff",
    "mls staff",
    "mlsstaff",
    "mls team",
    "moving & storage",
    "noaccess",
    "non member/vendor",
    "non-member",
    "non-member designated appraiser",
    "non-member designated participant",
    "non-member licensed appraiser",
    "non-member licensed subscriber",
    "non-member office staff",
    "non-member unlicensed assistant",
    "nonmembervendor",
    "office secretary",
    "office staff",
    "officestaff",
    "other",
    "personal assistant",
    "personal assistant, primary",
    "personal assistant, secondary out of state",
    "pest control",
    "photographer",
    "planning services",
    "primary affiliate",
    "primary home inspector",
    "primary home stager",
    "primary photographer",
    "primary radon inspector",
    "radon mitigation or inspection",
    "real estate related srv",
    "realtor appraiser",
    "realtor emeritus",
    "realtorappraiser",
    "roofing",
    "secondary affiliate",
    "secondary home inspector",
    "secondary photographer",
    "sold listings",
    "stager",
    "subscriber mls only",
    "title & escrow",
    "unlicensed assistant",
    "unlicensedassistant",
    "association staff",
    "head appraiser",
    "mls administrator",
    "office administrator",
    "photographer",
    "waive mls access",
    "nms",
    "rets subscriber",
    "appraiser associate",
    "data",
    "outside user",
    "secretary",
    "third party vendor",
    "appraiser secretary",
    "mls affiliate",
    "honorary member",
    "secondary appraiser",
    "designated appraiser",
    "secondary designated appraiser",
    "3",
    "24",
    "17",
    "2",
    "10",
    "7",
    "14",
    "5",
    "8",
    "12",
    "19",
    "21",
    "22",
    "23",
]

security_class_patterns = [
    "administrative",
    "af",
    "agent assistant",
    "ap",
    "ap - appraiser",
    "as",
    "ats - affiliate w\\tax so",
    "bangg",
    "bangk",
    "bangl",
    "bangm",
    "bangn",
    "bangp",
    "bangq",
    "base level user",
    "baseleveluser",
    "hoa",
    "ma - mls admin",
    "mls admin",
    "mls staff",
    "ms - mls staff",
    "na - no access",
    "no access",
    "noaccess",
    "non-realtor",
    "a2 - office assistant",
    "af - affiliates",
    "na - no access",
    "a3 - firm assistant",
    "a1 - individual assistant",
    "gov - government",
    "ae - association employee",
    "ms - mls staff",
    "sua - subscriber appraise",
    "ma - mls admin",
    "tsub - test subscriber",
    "oa",
    "od",
    "office level",
    "office not licensed",
    "onl - office not licensed",
    "og",
    "pa",
    "ph",
    "tp",
    "mpa - member participant",
    "ta - tarasoft admin",
    "tal - answer link",
    "imsomni - intramatrixsso",
    "imsomni - intramatrixsso",
    "ims - intramatrixsso",
    "wc - webapi contacts",
    "office staff",
    "board staff",
    "head appraiser",
    "licensed firm admin",
    "licensed office admin",
    "photographer",
    "unlicensed firm admin",
    "unlicensed office admin",
    "affiliate",
    "appraiser",
    "personal assistant",
    "reciprocal sso user",
    "mls agent trainer",
    "imsomni -intramatrixsso",
    "ats - affiliate w\tax sol",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
]
