member_type_patterns = [
    "cs administrative",
    "rets vendors",
    "waivered",
    "training",
    "mls access",
    "virtual tour",
    "mls",
    "rets vendor/access",
    "no member type",
    "staff",
    "mls only",
    "inspector",
    "board of directors",
    "agent/personal assistant/secondary",
    "staff/personal assistant",
    "non-mls",
    "appraiser/affiliate/mls only",
    "appraiser (secondary)",
    "appraiser manager",
    "unlicensed office staff",
    "cleaning services",
    "notary public",
    "thompson participants",
    "non-realtor salesperson",
    "no access",
    "association",
    "licensed office assistant",
    "full service app",
    "rets vendor",
    "appraisermgr",
    "inactive",
    "public svc mbr",
    "metro only",
    "sold only",
    "appraiser trainees",
    "assessor",
    "mls secretary",
    "imls admin",
    "reciprocal",
    "vendor",
    "admin",
    "appraisers",
    "clerical",
    "greenville user",
    "piedmont user",
    "rets user",
    "administrative",
    "administrator",
    "advertising",
    "affiliate",
    "appraisal",
    "appraiser assistant",
    "assistant (agent/firm/office level)",
    "association staff",
    "baseleveluser",
    "board staff",
    "book a showing",
    "construction/development",
    "estate sales services",
    "gift & retail services",
    "government designated realtor",
    "govt",
    "home warranty",
    "hospitality",
    "idx services",
    "inspectors",
    "insurance",
    "interior design/staging",
    "legal services",
    "lenders",
    "licensed assistant",
    "marketing",
    "military",
    "mls level",
    "mls team",
    "moving & storage",
    "non member/vendor",
    "non-member (designated/licensed/office staff/assistant)",
    "office secretary",
    "office staff",
    "other",
    "personal assistant",
    "pest control",
    "photographer",
    "planning services",
    "primary/secondary home inspector or stager",
    "radon mitigation",
    "real estate related srv",
    "realtor emeritus",
    "roofing",
    "stager",
    "title & escrow",
    "unlicensed assistant",
    "honorary member",
    "data",
    "outside user",
]

security_class_patterns = [
    "administrative",
    "af",
    "agent assistant",
    "ap",
    "ap - appraiser",
    "as",
    "hoa",
    "ats - affiliate w\\tax so",
    "bangg",
    "bangk",
    "bangl",
    "bangm",
    "bangn",
    "bangp",
    "bangq",
    "base level user",
    "ma - mls admin",
    "mls admin",
    "mls staff",
    "ms - mls staff",
    "na - no access",
    "noaccess",
    "non-realtor",
    "a2 - office assistant",
    "af - affiliates",
    "a3 - firm assistant",
    "a1 - individual assistant",
    "gov - government",
    "ae - association employee",
    "sua - subscriber appraise",
    "tsub - test subscriber",
    "oa",
    "od",
    "office level",
    "office not licensed",
    "onl - office not licensed",
    "og",
    "pa",
    "ph",
    "tp",
    "mpa - member participant",
    "ta - tarasoft admin",
    "tal - answer link",
    "imsomni - intramatrixsso",
    "ims - intramatrixsso",
    "wc - webapi contacts",
    "licensed/unlicensed firm or office admin",
    "photographer",
    "reciprocal sso user",
    "mls agent trainer",
    "ats - affiliate w\\tax sol",
]
